public enum State
{
    VerificarCasoPicc,
    ColetarAutorização,
    RecolherMateriais,
    LavarMaos,
    PrepararUniforme,
    MensurarCateter,
    PrepararCampo,
    LubrificarCateter,
    PrepararCateter,
    RealizarAntissepsia,
    TrocarLuvas,
    PrepararConjuntoIntrodutor,
    PrepararTorniquete,
    RealizarPuncture,
    RealizarIntroductionCompleta,
    RealizarTesteDePermeabilidade,
    FecharSistema,
    CobrirCateter
}